const DEFAULT_SYNC_TIMEOUT_MS = 10000
const DEFAULT_SYNC_BATCH_SIZE = 25
const DEFAULT_SYNC_INTERVAL_MS = 60000
const DEFAULT_RETRY_BASE_MS = 15000
const DEFAULT_MAX_SYNC_ATTEMPTS = 25
const DEFAULT_API_BASE_URL = String(process.env.API_BASE_URL || '').trim()
const DEFAULT_AUTH_PATH = 'auth/login'
const DEFAULT_PUSH_PATH = 'sync/events/batch'
const DEFAULT_PULL_PATH = 'sync/pull'
const DEFAULT_DEVICE_NAME = 'POS-LOCAL-01'
const SYNC_SOURCE = 'cardbastion-pos'

module.exports = {
  DEFAULT_SYNC_TIMEOUT_MS,
  DEFAULT_SYNC_BATCH_SIZE,
  DEFAULT_SYNC_INTERVAL_MS,
  DEFAULT_RETRY_BASE_MS,
  DEFAULT_MAX_SYNC_ATTEMPTS,
  DEFAULT_API_BASE_URL,
  DEFAULT_AUTH_PATH,
  DEFAULT_PUSH_PATH,
  DEFAULT_PULL_PATH,
  DEFAULT_DEVICE_NAME,
  SYNC_SOURCE,
}
